### ISSUE TITLE
Wring pop value after redis server restart

### ISSUE THREAD

**Issue by majood** [ServiceStack/Issues#655]
We use a blocking pop in our code, which works fine when the redis server is online. However, the very first pop after a redis server restart seem to return the queue name instead of the popped value, although the value is removed from the list. 

Is this expected behaviour? Is there anything special we need to do to handle redis server restarts when using blocking code? 

This simple console app reproduces the issue:
    class Program
    {
        protected internal static BasicRedisClientManager BasicRedisClientManager;

        static void Main(string[] args)
        {
            var host = "localhost";
            var port = "6379";
            var db = "9";

            RedisConfig.DefaultRetryTimeout = -1;

            var redisUri = $"{host}:{port}?db={db}&RetryTimeout=600000";

            BasicRedisClientManager = new BasicRedisClientManager(redisUri);
            var queue = "FormSaved";

            while (true)
            {
                Task.Run(() => BlockingReceive(queue));
                Thread.Sleep(1000);

                Console.WriteLine("Restart Redis and press Enter...");
                Console.ReadLine();

                Console.WriteLine("Enter something:");
                var item = Console.ReadLine();

                if (!string.IsNullOrWhiteSpace(item))
                {
                    using (var client = BasicRedisClientManager.GetClient())
                    {
                        client.AddItemToList(queue, item);
                    }

                    Console.WriteLine("Item added");
                }
            
                Thread.Sleep(1000);
            }
        }

        public static void BlockingReceive(string queue)
        {
            using (var client = BasicRedisClientManager.GetReadOnlyClient())
            {
                Console.WriteLine($"Listening to {queue}");

                var fromList = client.BlockingPopItemFromList(queue, TimeSpan.FromSeconds(60));
               
                Console.WriteLine($"Received:{JsonConvert.SerializeObject(fromList)}");
            }
        }
    }

**Comment by mythz** [comment]
I'm seeing the expected behavior and output:

```
Listening to FormSaved
Restart Redis and press Enter...

Enter something:
key1
Item added
Listening to FormSaved
Received:"key1"
Restart Redis and press Enter...

Enter something:
key2
Item added
Listening to FormSaved
Received:"key2"
Restart Redis and press Enter...

Enter something:
key3
Item added
Listening to FormSaved
Received:"key3"
Restart Redis and press Enter...
```

I'm assuming you're also using the latest version?

**Comment by majood** [comment]
Yes, I've tried with an older version (4.5.14) and now with the very latest and consistently the same behavior.

I've also tried with different versions of Redis server.

You did restart the server manually right? :)

```
Listening to FormSaved
Restart Redis and press Enter...

Enter something:
Hello
Item added
Received:"Hello"
Listening to FormSaved
Restart Redis and press Enter...

Enter something:
After restart
Item added
Received:"FormSaved"
Listening to FormSaved
Restart Redis and press Enter...

Enter something:
Without restart
Received:"Without restart"
Item added
Listening to FormSaved
Restart Redis and press Enter...
```

**Comment by majood** [comment]
Can I provide more information?

**Comment by majood** [comment]
I give up for today!
FLUSHALL didn't help. It's been consistent every time, except a few very rare cases, so I'm a bit surprised you were not able to reproduce it. I've even tried with a freshly installed Redis server, without any luck. 

There is nothing wrong with the posted code you say?
Could it be some server configuration thing?

**Comment by majood** [comment]
I've played with this a little bit more and somehow I suspect the retry logic to be doing something fishy.

Having a blocking pop and RetryTimeout to something like 20000 almost always results in first popping the list name, and then another pop with the value. The value is sometimes correct and sometimes corrupted and results in a RedisResponseException: Unknown reply on multi-request: 

This strange behaviour goes away by setting RedisConfig.DefaultRetryTimeout = 0. In this case shutting down the redis server results in System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host, immediately, and retrying to re-connect manually (while loop) will eventually succeed.

I've also notices that sometimes if the restart goes fast, the connection is somehow not broken, but upon next lpush results in ServiceStack.Redis.RedisRetryableException: [23:34:51.304] No more data, sPort: 61495, LastCommand:. In this case the lpushed value is lost!

I don't know if any of this makes sense, but it feels like i'm not doing anything strange, but just trying to get the very basic functionality to work and it isn't working as supposed to.

**Comment by majood** [comment]
Thanks a lot!
Gave the v5.4.1 a quick run and it seems that server restarts are handled correctly now. No exceptions, no wrong values, and no values lost. At least for blocking pops.

However.. :)

I'm seeing a similar type of issue with subscriptions.
```
while (true)
{
    try
    {
        using (var client = BasicRedisClientManager.GetClient())
        {
            Console.WriteLine("Subscribing");
            var subscription = client.CreateSubscription();
            subscription.OnMessage = (channel, message) =>
            {
                Console.WriteLine($"Received {message} from channel:{channel}");
            };
            subscription.SubscribeToChannels("theChannel");
        }
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }
}
```
The code works fine until the redis server is restarted, after which a `SocketException: An existing connection was forcibly closed by the remote host` is thrown. The problem arise when getting a new client in the next iteration of the loop. The new client does not get any published messages, maybe because of problems re-connecting to the redis server?

The following output is generated (messages are published using redis-cli):
```
Subscribing
Received Hello from channel:theChannel
Received World! from channel:theChannel
Received Test from channel:theChannel
Received 1 from channel:theChannel
Received 2 from channel:theChannel
Received 3 from channel:theChannel
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.ReadByte()
   at ServiceStack.Redis.RedisNativeClient.ReadMultiData()
   at ServiceStack.Redis.RedisNativeClient.ReceiveMessages()
   at ServiceStack.Redis.RedisSubscription.SubscribeToChannels(String[] channels)
   at TestRedis.Program.SubscribeIssue() in C:\Users\majd\Desktop\TestRedis\TestRedis\TestRedis\Program.cs:line 130
Subscribing
```

The problem can be solved by doing a `Thread.Sleep(5000)` in the catch clause, maybe because this will give the redis server enough time to be back again and the new client will not face any issues when connecting.

Could this be a re-connect bug as well? Let me know if you need more information?

**Comment by mythz** [comment]
The Exception is as expected when it’s not unable to connect to the redis server and it takes a while to be able to recover.

**Comment by majood** [comment]
Have you had any time to look at the above? Would be good to know if you are able to reproduce the issue and how to handle this issue in general - i.e. how to deal with the fact that it is possible to receive a client that form some reason has not established a working connection, but without any trace of the fact?

**Comment by majood** [comment]
We'll take a look at the managed RedisPubSubServer, maybe that's what we need.
Still I think the issue described is actually not related to the subscription.
What's the expected behaviour of having a redis server offline, trying to get a redis client and at the same time starting the redis server?

I'm seeing the following:

```
RedisConfig.DefaultConnectTimeout = 20 * 1000;
RedisConfig.DefaultRetryTimeout = 20 * 1000;
BasicRedisClientManager = new RedisManagerPool(redisUri);
try
{
    using (var client = BasicRedisClientManager.GetClient())
    {
        Console.WriteLine("Blocking...");
        var fromList = client.BlockingRemoveStartFromList("AnyQueue", TimeSpan.FromMinutes(20));
        Console.WriteLine($"Received:{JsonConvert.SerializeObject(fromList)}");
    }
}
catch (Exception e)
{
    Console.WriteLine(e);
}
```
Running the above code with the redis server stopped, and without doing anything, will throw an exception after 20 seconds as expected.

However, running the code, and then starting the redis server will end up with the call to GetClient() to never return and no time out exception. Nothing printed to the console.

Expected? 
This is somewhat similar to the other issue in which the call to GetClient returned, but the client was not working properly and not responding to messages. Again, I think this is not related to the subscription.

**Comment by mythz** [comment]
Not able to repro this, I can run the code, restart the redis server and then push an item to the list that the client is blocking listening to from redis-cli with "LPUSH AnyQueue A" and the result is the same as if the redis-server was never restarted, i.e:

```csharp
Blocking...
Received: A
```

> Note: Please use the `.Dump()` or `.ToJson()` extension methods in your code examples instead of forcing an extra 3rd party dependency with `JsonConvert`.

**Comment by mythz** [comment]
Should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/e952c923da202c97ce25300e6305ab04426f43b0), this change is available from the latest v5.4.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Comment by majood** [comment]
Thanks for your help with this, but unfortunately the change did not resolve the issue on my end. The same result as before, hanging on the getClient call.

**Comment by mythz** [comment]
As you already had v5.4.1 installed you would need to [clear your NuGet packages cache](https://docs.servicestack.net/myget#redownloading-myget-packages).

**Comment by majood** [comment]
Yes, that was it! Both issues I was experiencing disappeared with the last commit! Thanks a lot! Will give it some more testing tomorrow, but everything seems to work as expected now anyways...

By the way, is there any good reason to change the `DeactivatedClientsExpiry = TimeSpan.FromMinutes(1);` from the default?

**Comment by majood** [comment]
Hello again, unfortunately we are seeing some more problems...
Everything was working in the demo app after the fixes where implemented, but when testing in our product we are seeing some more problems. I think they are related to the fact that you have multiple simultaneous blocking calls. When having this, and doing a redis server restart, the responses are inconsistent, sometimes everything works, sometimes some clients get exceptions, and sometimes we get unresponsive clients again. The exceptions happen either during the restart itself, or when pushing data to a queue.

This is the code I'm using now:

```
class Program
    {
        protected internal static RedisManagerPool BasicRedisClientManager;

        static void Main(string[] args)
        {
            var host = "localhost";
            var port = "6379";
            var db = "9";
            RedisConfig.DefaultConnectTimeout = 20 * 1000;
            RedisConfig.DefaultRetryTimeout = 20 * 1000;
            RedisConfig.DeactivatedClientsExpiry = TimeSpan.Zero;

            BasicRedisClientManager = new RedisManagerPool($"{host}:{port}?db={db}");
            
            MultipleBlocking(3);

            Console.ReadLine();
        }

        private static void MultipleBlocking(int count)
        {
            for (int i = 0; i < count; i++)
            {
                var queue = $"Queue {i + 1}";
                RunTask(() => BlockingRemoveStartFromList(queue), $"Receive from {queue}");
            }
        }
        public static void BlockingRemoveStartFromList(string queue)
        {
            using (var client = BasicRedisClientManager.GetClient() as RedisClient)
            {
                client.Ping();
                Console.WriteLine($"Listening to {queue}");

                var fromList = client.BlockingRemoveStartFromList(queue, TimeSpan.FromHours(10));
                Console.WriteLine($"Received:{fromList.Dump()}");
            }
        }

        private static void RunTask(Action action, string name)
        {
            Task.Run(() =>
            {

                while (true)
                {
                    try
                    {
                        Console.WriteLine($"Invoking {name}");
                        action.Invoke();
                    }
                    catch (Exception exception)
                    {
                        Console.WriteLine($"Exception in {name}: {exception}");
                        //Thread.Sleep(5000);// Give redis some time to wake up!
                    }

                    Thread.Sleep(100);
                }

            });
        }
    }
```

To reproduce:
- Start the program
- Submit data using cli to any of the queues
- Restart redis server
--> Exceptions and in some instances (not all the time) we manage to get a client that is not responding to any messages, which is what is worrying.
The expectation is no exceptions and all clients continue to respond to messages after restart.

You might need to test a few times as it is not consistent, but happens occasionaly.
Again, we only see this behaviour when we have more than one call at a time.

Please let me know if you know why this is happening or if you need further clarification.

**Comment by mythz** [comment]
Sorry trying to repro the error and debug the issue ended up being too time consuming so went to work on higher priority stuff.

I've returned to look into it and added a [unique client Id which is now included in the logs](https://github.com/ServiceStack/ServiceStack.Redis/commit/098c425b4519be56f858a6c80a60101403d0b48c) so we can more easily track individual clients. I've also added more verbose debug logging which can be enabled with:

```csharp
RedisConfig.EnableVerboseLogging = true;
```

Was able to track the issue resulting from the client not resending the command when needed which should be resolved in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/071b8fe5806dbfd58ec4c2090fa8d11fb6fa9363).

After this change I was no longer able to repro the issue after 20 restarts, testing each queue after each restart.

I've also changed the default of `DeactivatedClientsExpiry` to `TimeSpan.Zero` so you'll no longer need to include it in your configuration.

This change is available from the latest v5.4.1 which is now on MyGet, as you had v5.4.1 installed you'll need to [clear your NuGet packages cache](https://docs.servicestack.net/myget#redownloading-myget-packages) to download the latest version.

**Comment by majood** [comment]
Hello, 

Opening up this issue again, not really sure whether the exceptions we are seeing now are related or not though. 

We are seeing a few exception in production that we are a little bit worried about. The exceptions are outside of our control and we want to confirm where the problem might be.  
Are those exceptions expected? We can provide more information if needed, and most importantly we want to rule out the possibility of loosing data because of an exception after a dequeue.

Do these exceptions tell you anything?
Let me know if you need any further clarification. 

`ServiceStack.Redis.RedisResponseException: Unknown reply on multi-request: 43OK
"ServiceStack.Redis.RedisResponseException: Unknown reply on multi-request: 43OK
   at ServiceStack.Redis.RedisNativeClient.ReadMultiData() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 1036
   at ServiceStack.Redis.RedisSubscription.SubscribeToChannelsMatching(String[] patterns) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisSubscription.cs:line 56
   at Viedoc.Redis.Cache.RedisCache.SubscribeToExpire(String keyPrefix, Action`1 onExpireAction) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\Cache\CacheService.cs:line 211"
`

`System.NotSupportedException: The Read method cannot be called when another read operation is pending.
"ServiceStack.Redis.RedisException: [13:18:53.515] Unable to Connect: sPort: 49807, Error: The Read method cannot be called when another read operation is pending.
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.ReadByte()
   at ServiceStack.Redis.RedisNativeClient.ReadMultiData() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 998
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 628 ---> System.NotSupportedException: The Read method cannot be called when another read operation is pending.
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.ReadByte()
   at ServiceStack.Redis.RedisNativeClient.ReadMultiData() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 998
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 628
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 378
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 655
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 745
   at ServiceStack.Redis.RedisSubscription.SubscribeToChannelsMatching(String[] patterns) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisSubscription.cs:line 51
   at Viedoc.Redis.Cache.RedisCache.SubscribeToExpire(String keyPrefix, Action`1 onExpireAction) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\Cache\CacheService.cs:line 211"
`

`ServiceStack.Redis.RedisRetryableException: [04:29:27.702] No more data, sPort: 58192, LastCommand:
"ServiceStack.Redis.RedisException: Exceeded timeout of 00:01:00 ---> ServiceStack.Redis.RedisRetryableException: [04:29:27.702] No more data, sPort: 58192, LastCommand: 
   at ServiceStack.Redis.RedisNativeClient.CreateRetryableResponseError(String error) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 368
   at ServiceStack.Redis.RedisNativeClient.ReadMultiData() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 1036
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 628
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 670
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 745
   at ServiceStack.Redis.RedisNativeClient.BLPop(String[] listIds, Int32 timeOutSecs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient.cs:line 1419
   at ServiceStack.Redis.RedisNativeClient.BLPopValue(String listId, Int32 timeOutSecs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient.cs:line 1427
   at ServiceStack.Redis.RedisClient.BlockingRemoveStartFromList(String listId, Nullable`1 timeOut) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisClient_List.cs:line 132
   at Viedoc.Redis.MessageQueue.RedisMessageQueueService.DequeueBlocking[T](String queueName, Nullable`1 timeout, Boolean clearQueue) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\MessageQueue\MessageQueueService.cs:line 137"
`

`System.NullReferenceException: Object reference not set to an instance of an object.
"ServiceStack.Redis.RedisException: [01:30:57.210] Unable to Connect: sPort: 63046, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.Connect() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 119
   at ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 321
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 595 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.Connect() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 119
   at ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 321
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 595
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 378
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 655
   at ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 730
   at ServiceStack.Redis.RedisClient.<>c__DisplayClass131_0`1.<Get>b__0(RedisClient r) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisClient.ICacheClient.cs:line 49
   at ServiceStack.Redis.RedisClient.Exec[T](Func`2 action) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisClient.ICacheClient.cs:line 29
   at Viedoc.Redis.Cache.RedisCache.Get[T](String cacheId) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\Cache\CacheService.cs:line 37
   at Viedoc.Redis.Cache.RedisCache.UserCacheAdd[T](Int32 loginId, String key, T value) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\Cache\CacheService.cs:line 91"
`

`ServiceStack.Redis.RedisRetryableException: [22:54:44.820] No more data, sPort: 62876, LastCommand:
"ServiceStack.Redis.RedisException: Exceeded timeout of 00:01:00 ---> ServiceStack.Redis.RedisRetryableException: [22:54:44.820] No more data, sPort: 62876, LastCommand: 
   at ServiceStack.Redis.RedisNativeClient.CreateRetryableResponseError(String error) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 368
   at ServiceStack.Redis.RedisNativeClient.ReadMultiData() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 1036
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 628
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 670
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 745
   at ServiceStack.Redis.RedisNativeClient.BLPop(String[] listIds, Int32 timeOutSecs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient.cs:line 1419
   at ServiceStack.Redis.RedisNativeClient.BLPopValue(String listId, Int32 timeOutSecs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient.cs:line 1427
   at ServiceStack.Redis.RedisClient.BlockingRemoveStartFromList(String listId, Nullable`1 timeOut) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisClient_List.cs:line 132
   at Viedoc.Redis.MessageQueue.RedisMessageQueueService.DequeueBlocking[T](String queueName, Nullable`1 timeout, Boolean clearQueue) in "
`

`System.NotSupportedException: The Write method cannot be called when another write operation is pending.
"ServiceStack.Redis.RedisException: [00:01:38.479] Unable to Connect: sPort: 62909, Error: The Write method cannot be called when another write operation is pending.
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 531
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 626 ---> System.NotSupportedException: The Write method cannot be called when another write operation is pending.
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 531
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 626
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 378
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 655
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 745
   at ServiceStack.Redis.RedisSubscription.SubscribeToChannelsMatching(String[] patterns) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisSubscription.cs:line 51
   at Viedoc.Redis.Cache.RedisCache.SubscribeToExpire(String keyPrefix, Action`1 onExpireAction) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\Cache\CacheService.cs:line 211
   at Viedoc.Worker.RunTask.ProcessAutoSubjectUnlock.Run() in C:\agents\dev1azure\_work\8\s\Viedoc.Worker\IntervalTask\Tasks\ProcessAutoSubjectUnlock.cs:line"
`

`ServiceStack.Redis.RedisRetryableException: [02:23:35.369] No more data, sPort: 64588, LastCommand:
"ServiceStack.Redis.RedisRetryableException: [02:23:35.369] No more data, sPort: 64588, LastCommand: 
   at ServiceStack.Redis.RedisNativeClient.CreateRetryableResponseError(String error) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 368
   at ServiceStack.Redis.RedisNativeClient.ReadMultiData() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 1036
   at ServiceStack.Redis.RedisSubscription.SubscribeToChannelsMatching(String[] patterns) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisSubscription.cs:line 56
   at Viedoc.Redis.Cache.RedisCache.SubscribeToExpire(String keyPrefix, Action`1 onExpireAction) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\Cache\CacheService.cs:line 211
   at Viedoc.Worker.RunTask.ProcessAutoSubjectUnlock.Run() in C:\agents\dev1azure\_work\8\s\Viedoc.Worker\IntervalTask\Tasks\ProcessAutoSubjectUnlock.cs:line 41"
`

`System.IndexOutOfRangeException: Index was outside the bounds of the array.
"System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Contains(T item)
   at Viedoc.Redis.ServiceStackRedis.RedisClientFactory.Create(IRedisClientsManager clientsManager) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\ServiceStackRedis\RedisManagerPoolFactory.cs:line 50
   at Viedoc.Redis.Cache.RedisCache.SubscribeToExpire(String keyPrefix, Action`1 onExpireAction) in C:\agents\dev1azure\_work\8\s\Viedoc.Redis\Cache\CacheService.cs:line 193
   at Viedoc.Worker.RunTask.ProcessAutoSubjectUnlock.Run() in C:\agents\dev1azure\_work\8\s\Viedoc.Worker\IntervalTask\Tasks\ProcessAutoSubjectUnlock.cs:line 41"

`

**Comment by mythz** [comment]
This looks like a classic race concurrency issue where you have multiple threads accessing the same non ThreadSafe `IRedisClient` instance concurrently. Only the `IRedisClientsManager` factories are threadsafe and what all threads should use to resolve their own redis client.

You can enable the [RedisConfig.AssertAccessOnlyOnSameThread](https://forums.servicestack.net/t/junk-values-while-reading-from-redis/5947/22) debug feature to help identify where multiple threads could be using the same instance concurrently.

Things you can look out for in your code-base to prevent against concurrent usage of a `IRedisClient` instance:
 - use redis client within a using statement
 - never use a client instance after its disposed
 - never use (or return) a "server collection" (e.g. Redis.Lists[]) after the client has been disposed
 - never keep a singleton or static instance to a redis client (just the IRedisClientsManager factory)
 - never use the same redis client in multiple threads, have each thread resolve their own client from the factory within a using statement

They're the main issues that would cause this.
